### ISSUE TITLE
Can't open

### ISSUE THREAD

**Issue by louanfontenele** [Xevion/factorio-achievements-fixer#1]
Can't open the file

**Comment by Xevion** [comment]
- This project is not released, finished, or even functioning. I have not published the functional code. I'm not sure what you were expecting - but whatever it was, it's not available to you, or anyone else.
- Your issue is not helpful or capable of being solved, even if it was published against a functioning repository. How exactly could I help you with exactly four words describing your issue?

**Comment by louanfontenele** [comment]
> * This project is not released, finished, or even functioning. I have not published the functional code. I'm not sure what you were expecting - but whatever it was, it's not available to you, or anyone else.
> * Your issue is not helpful or capable of being solved, even in the case that it was published against a functioning repository. How exactly do you expect be to help you with exactly four words describing your issue?


I saw a PUBLIC repository about a topic I was looking for, believing it would work, but there is NO information that the code is incomplete and non-functional. I tried to open it and all that appears is a blank window with nothing else.

I created an issue exactly to report that it doesn't work.

More information is missing.

But I appreciate your information.

I've already resolved it with another repository. But even so, thanks.

**Comment by Xevion** [comment]
> but there is NO information that the code is incomplete and non-functional

![image](https://github.com/user-attachments/assets/bd2b62c7-10c7-4261-ab4f-166a04e5b959)

I otherwise would be pointing to the non-existence of any relevant code in the entire project (only 1 `.cs` file) on the `master` branch.
